### ISSUE TITLE
Clarify role of SIZE for arrays and objects

### ISSUE THREAD

**Issue by ColinH** [stephenberry/beve#4]
For arrays and objects the `SIZE` field can be interpreted in one of two ways,

1. the number of array elements or object members, or
2. the total number of bytes of all array elements or object members.

I'm _assuming_ the first option is used, but would greatly prefer and suggest this to be explicitly stated in `README.md`.

**Comment by ColinH** [comment]
Great for arrays and objects!

Though for UTF-8 strings I have to ask, are you sure you mean "characters"?

**Comment by stephenberry** [comment]
Valid point, it's only a character count for ASCII. I'll change the wording.
